stages:
  - test
  - deploy

test:
  stage: test
  parallel:
    matrix:
      - PYVERSION:
        - '3.9'
        - '3.10'
        - '3.11'
        - '3.12'
        - '3.13'
  image: "python:$PYVERSION"
  script:
    - pip install -q -r requirements.txt
    - pip install -q .
    - cd testsuite
    - pytest test_all.py --junitxml=$CI_PROJECT_DIR/testsuite_results.xml
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA"
    when: always
    reports:
      junit:
        - testsuite_results.xml

pages:
  stage: deploy
  image: sphinxdoc/sphinx
  script:
    - make -C docs html
    - mv docs/_build/html public
  artifacts:
    paths:
    - public
  only:
  - master
