stages:
  - test
  - deploy
  - publish

test:
  stage: test
  parallel:
    matrix:
      - PYVERSION:
        - '3.9'
        - '3.10'
        - '3.11'
        - '3.12'
        - '3.13'
  image: "python:$PYVERSION"
  script:
    - pip install -q -r requirements.txt
    - pip install -q .
    - cd testsuite
    - pytest test_all.py --cov=hdlmake --cov-report=term --cov-report=xml:coverage.xml --junitxml=$CI_PROJECT_DIR/testsuite_results.xml
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA"
    when: always
    reports:
      junit:
        - testsuite_results.xml
      coverage_report:
        coverage_format: cobertura
        path: testsuite/coverage.xml

pages:
  stage: deploy
  image: sphinxdoc/sphinx
  script:
    - make -C docs html
    - mv docs/_build/html public
  artifacts:
    paths:
    - public
  only:
  - master

pypi-publish:
  image: python:latest
  stage: publish
  variables:
    TWINE_USERNAME: __token__
    TWINE_PASSWORD: $GIT_TWINE_TOKEN
    TWINE_REPOSITORY: testpypi
  script:
    - pip install build twine
    - python -m build
    - python -m twine check dist/*
    - python -m twine upload --verbose -r $TWINE_REPOSITORY dist/*
  rules:
    - if: $CI_COMMIT_TAG
